### ISSUE TITLE
unity 2018.3.1 error

### ISSUE THREAD

**Issue by hanbim520** [maajor/OSMTrafficSim#1]
InvalidOperationException: The NativeArray has been deallocated, it is not allowed to access it
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckWriteAndThrowNoEarlyOut (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) <0x39240290 + 0x00052> in <d616be05755d41a089810b5c14e4dd50>:0
Unity.Collections.NativeArray`1[T].CheckElementWriteAccess (System.Int32 index) (at D:/unity/Runtime/Export/NativeArray/NativeArray.cs:130)
Unity.Collections.NativeArray`1[T].set_Item (System.Int32 index, T value) (at D:/unity/Runtime/Export/NativeArray/NativeArray.cs:145)
OSMTrafficSim.InstanceRenderer.Batch (Unity.Entities.Entity ent) (at Assets/Code/Rendering/InstanceRenderer.cs:76)
OSMTrafficSim.InstanceRenderingSystem.Render () (at Assets/Code/Rendering/InstanceRenderingSystem.cs:101)

**Comment by maajor** [comment]
Thanks, looks like Unity have some api change in 2018.3.1, I will look after it later.

**Comment by maajor** [comment]
solved.
