### ISSUE TITLE
Entities Version 1.0.16

### ISSUE THREAD

**Issue by Ojayyy** [maajor/OSMTrafficSim#4]
Do you see a way to make this work with the Entities 1.0.16 version?

**Comment by maajor** [comment]
> Do you see a way to make this work with the Entities 1.0.16 version?

sure! I can have a try

**Comment by maajor** [comment]
working on it, but harder than I thought
https://github.com/maajor/OSMTrafficSim/tree/maajor/feat/u2023-entities1

**Comment by Ojayyy** [comment]
Wow, thank you for your effort!
Unfortunately, I get some error messages starting the TrafficModel scene in the editor.
Steps to reproduce:
-	Installed Unity 2023.1.20f1 from the hub – Installation from the scratch
-	Opened OSMTrafficSim (u2023) for Windows
-	Checked the Package Manager (see Picture below)
-	Installed URP, created a URP Pipeline and set Rendering Path to Forward+

Again, thank you and I really appreciate your work!

![image](https://github.com/maajor/OSMTrafficSim/assets/13174622/bf2fda0d-d758-45f4-b843-413df4163ddd)
![image](https://github.com/maajor/OSMTrafficSim/assets/13174622/581e4339-3fe6-43b6-96c0-9b125d45c17f)
![image](https://github.com/maajor/OSMTrafficSim/assets/13174622/95879583-fb20-427f-a20b-ae4091c2f4ab)
Exception: This method should have been replaced by source gen.
OSMTrafficSim.VehicleSystem.Update () (at Assets/Code/Traffic/VehicleSystem.cs:104)
Unity.Entities.ComponentSystemGroup.UpdateAllSystems () (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:739)
UnityEngine.Debug:LogException(Exception)
Unity.Debug:LogException(Exception) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Stubs/Unity/Debug.cs:19)
Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:744)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:697)
Unity.Entities.SystemBase:Update() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/SystemBase.cs:418)
Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at [./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ScriptBehaviourUpdateOrder.c](mailto:./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ScriptBehaviourUpdateOrder.c)

![image](https://github.com/maajor/OSMTrafficSim/assets/13174622/19b05c9e-1cba-495e-a2c2-b8b7937470cb)
InvalidOperationException: The previously scheduled job VehicleSystem:WriteSenseResultJob writes to the ComponentTypeHandle<OSMTrafficSim.HitResult> WriteSenseResultJob.JobData.HitResult. You must call JobHandle.Complete() on the job VehicleSystem:WriteSenseResultJob, before you can read from the ComponentTypeHandle<OSMTrafficSim.HitResult> safely.
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckReadAndThrowNoEarlyOut (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) (at <36128ec596ab42c8af4441b8e0cdd33a>:0)
Unity.Entities.ComponentSafetyHandles.CompleteWriteDependency (Unity.Entities.TypeIndex typeIndex) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSafetyHandles.cs:286)
Unity.Entities.ComponentDependencyManager.CompleteWriteDependency (Unity.Entities.TypeIndex type) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentDependencyManager.cs:364)
Unity.Entities.EntityQueryImpl.ToComponentDataArray[T] (Unity.Collections.AllocatorManager+AllocatorHandle allocator, Unity.Entities.EntityQuery outer) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Iterators/EntityQuery.cs:1067)
Unity.Entities.EntityQuery.ToComponentDataArray[T] (Unity.Collections.AllocatorManager+AllocatorHandle allocator) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Iterators/EntityQuery.cs:2587)
OSMTrafficSim.VehicleSystem.Update () (at Assets/Code/Traffic/VehicleSystem.cs:78)
Unity.Entities.ComponentSystemGroup.UpdateAllSystems () (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:739)
UnityEngine.Debug:LogException(Exception)
Unity.Debug:LogException(Exception) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Stubs/Unity/Debug.cs:19)
Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:744)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:697)
Unity.Entities.SystemBase:Update() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/SystemBase.cs:418)
Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ScriptBehaviourUpdateOrder.cs:526)

![image](https://github.com/maajor/OSMTrafficSim/assets/13174622/45143554-83d3-4bf1-814a-f838c4c8a580)

**Comment by maajor** [comment]
> Wow, thank you for your effort! Unfortunately, I get some error messages starting the TrafficModel scene in the editor. Steps to reproduce:
> 
> * Installed Unity 2023.1.20f1 from the hub – Installation from the scratch
> * Opened OSMTrafficSim (u2023) for Windows
> * Checked the Package Manager (see Picture below)
> * Installed URP, created a URP Pipeline and set Rendering Path to Forward+
> 
> Again, thank you and I really appreciate your work!
> 
> ![image](https://private-user-images.githubusercontent.com/13174622/336856474-bf2fda0d-d758-45f4-b843-413df4163ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTYxNDcsIm5iZiI6MTcxNzU5NTg0NywicGF0aCI6Ii8xMzE3NDYyMi8zMzY4NTY0NzQtYmYyZmRhMGQtZDc1OC00NWY0LWI4NDMtNDEzZGY0MTYzZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEzNTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZDY1OWIwMjZjYmNjMGFjZjMyZWZkZmY1MDM0OTQ1ZDdmMTQwMTVlZGFlMjdjYzE5YzMzZTJmOTYxNTlkNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LF_nZEDwqte4b1BgJRYVfne-32F19_tDyaN4LLt4XDI) ![image](https://private-user-images.githubusercontent.com/13174622/336856558-581e4339-3fe6-43b6-96c0-9b125d45c17f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTYxNDcsIm5iZiI6MTcxNzU5NTg0NywicGF0aCI6Ii8xMzE3NDYyMi8zMzY4NTY1NTgtNTgxZTQzMzktM2ZlNi00M2I2LTk2YzAtOWIxMjVkNDVjMTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEzNTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwOTVhYWQ2NDUzYzU4NjliOTFhMDI3MGYxNDZlZjE4YjAxZGE4YzI2ZTQ1MzNhYmQ5ZjJiZTMyODBkNDQwN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MfzvCx0z06CzpnOzogVttCmSD_NdgR3E687S3FuWTpA) ![image](https://private-user-images.githubusercontent.com/13174622/336856615-95879583-fb20-427f-a20b-ae4091c2f4ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTYxNDcsIm5iZiI6MTcxNzU5NTg0NywicGF0aCI6Ii8xMzE3NDYyMi8zMzY4NTY2MTUtOTU4Nzk1ODMtZmIyMC00MjdmLWEyMGItYWU0MDkxYzJmNGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEzNTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NDRkMDQ2YzIwMWM0OTUyODE2MmE5N2QxMzg0MGNlZDIzMjc1NzlkYTQ0MzIxMjY3ZDY4NDVlNjk1YmJjMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyt2-eIcIzNsq8sNdLtj7MVO-7XpxGC8ll5FUqQPycI) Exception: This method should have been replaced by source gen. OSMTrafficSim.VehicleSystem.Update () (at Assets/Code/Traffic/VehicleSystem.cs:104) Unity.Entities.ComponentSystemGroup.UpdateAllSystems () (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:739) UnityEngine.Debug:LogException(Exception) Unity.Debug:LogException(Exception) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Stubs/Unity/Debug.cs:19) Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:744) Unity.Entities.ComponentSystemGroup:OnUpdate() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:697) Unity.Entities.SystemBase:Update() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/SystemBase.cs:418) Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at [./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ScriptBehaviourUpdateOrder.c](mailto:./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ScriptBehaviourUpdateOrder.c)
> 
> ![image](https://private-user-images.githubusercontent.com/13174622/336856753-19b05c9e-1cba-495e-a2c2-b8b7937470cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTYxNDcsIm5iZiI6MTcxNzU5NTg0NywicGF0aCI6Ii8xMzE3NDYyMi8zMzY4NTY3NTMtMTliMDVjOWUtMWNiYS00OTVlLWEyYzItYjhiNzkzNzQ3MGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEzNTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZDY4ZTYxNzRlZGFjZjkzY2QxMzkwOGM5N2MzYWI0YzYzZTY4YzNkMzIyNWY3N2YyZDRkODM5MmYxNWRmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T4qlJAXmcM0PJeqsZjlK3PjdsfUj3iIljbHT896E-Ps) InvalidOperationException: The previously scheduled job VehicleSystem:WriteSenseResultJob writes to the ComponentTypeHandle<OSMTrafficSim.HitResult> WriteSenseResultJob.JobData.HitResult. You must call JobHandle.Complete() on the job VehicleSystem:WriteSenseResultJob, before you can read from the ComponentTypeHandle<OSMTrafficSim.HitResult> safely. Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckReadAndThrowNoEarlyOut (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) (at <36128ec596ab42c8af4441b8e0cdd33a>:0) Unity.Entities.ComponentSafetyHandles.CompleteWriteDependency (Unity.Entities.TypeIndex typeIndex) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSafetyHandles.cs:286) Unity.Entities.ComponentDependencyManager.CompleteWriteDependency (Unity.Entities.TypeIndex type) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentDependencyManager.cs:364) Unity.Entities.EntityQueryImpl.ToComponentDataArray[T] (Unity.Collections.AllocatorManager+AllocatorHandle allocator, Unity.Entities.EntityQuery outer) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Iterators/EntityQuery.cs:1067) Unity.Entities.EntityQuery.ToComponentDataArray[T] (Unity.Collections.AllocatorManager+AllocatorHandle allocator) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Iterators/EntityQuery.cs:2587) OSMTrafficSim.VehicleSystem.Update () (at Assets/Code/Traffic/VehicleSystem.cs:78) Unity.Entities.ComponentSystemGroup.UpdateAllSystems () (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:739) UnityEngine.Debug:LogException(Exception) Unity.Debug:LogException(Exception) (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/Stubs/Unity/Debug.cs:19) Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:744) Unity.Entities.ComponentSystemGroup:OnUpdate() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ComponentSystemGroup.cs:697) Unity.Entities.SystemBase:Update() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/SystemBase.cs:418) Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at ./Library/PackageCache/com.unity.entities@1.0.16/Unity.Entities/ScriptBehaviourUpdateOrder.cs:526)
> 
> ![image](https://private-user-images.githubusercontent.com/13174622/336856963-45143554-83d3-4bf1-814a-f838c4c8a580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTYxNDcsIm5iZiI6MTcxNzU5NTg0NywicGF0aCI6Ii8xMzE3NDYyMi8zMzY4NTY5NjMtNDUxNDM1NTQtODNkMy00YmYxLTgxNGEtZjgzOGM0YzhhNTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDEzNTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkODFjMWUxOGU2MWUzY2I0MDdmMzA3YzhlMGIyMTJiOGRhM2JmMzA0ZmY2OGFlMDg5YzYzY2JkMmY5NmY3YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c0ksOJSQQGuh2yPzOLlB3PiOP3wabldSkREeLysKq0s)

Yes, thanks for your report. There are still some errors, I am still working on it. Seems Entities 1.0 overhaul many previous designs 😢

**Comment by maajor** [comment]
Ok so, I already made vehicle works,
on branch https://github.com/maajor/OSMTrafficSim/tree/maajor/feat/u2023-entities1
However, I disabled pedestrians, since the shader migration to URP seems a bit painful. I will migrate the rest later. 

![image](https://github.com/maajor/OSMTrafficSim/assets/4011861/1a8a16c6-cb64-4341-84e4-3938a03aefe2)

**Comment by Ojayyy** [comment]
> Ok so, I already made vehicle works, on branch https://github.com/maajor/OSMTrafficSim/tree/maajor/feat/u2023-entities1 However, I disabled pedestrians, since the shader migration to URP seems a bit painful. I will migrate the rest later.
> 
> ![image](https://private-user-images.githubusercontent.com/4011861/336896221-1a8a16c6-cb64-4341-84e4-3938a03aefe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDY4OTQsIm5iZiI6MTcxNzYwNjU5NCwicGF0aCI6Ii80MDExODYxLzMzNjg5NjIyMS0xYThhMTZjNi1jYjY0LTQzNDEtODRlNC0zOTM4YTAzYWVmZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTY1NjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZiMDBjZGRkMDgxZmNjMjQ0ZDAzZWRhYTllMWM2M2YwMzllZDJlMzVlNzMyMzI0ZWIzYWQzOWRhNWRhNmEwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pI86R1Jxb3xz5kPazKB8i4oQzlHCRGL2vZ2KriYmcow)

Nice! :-) The Traffic is what I'm looking for. I'll play a little bit with and give you feedback.
Thx!

**Comment by maajor** [comment]
Pedestrians upgraded, issue is auto closed.
Let me know if there is still any issue!
